InstitutMaupertuis/fanuc_grinding

grinding_rviz_plugin/src/path_planning_widget.cpp
grinding_rviz_plugin/src/path_planning_widget.h

Nothing very functional, mostly GUI simplification/cleaning.
- The angle is entered in degrees and converted/sent as radians.
- The grinder diameter and depth of pass are entered in millimeters and converted/sent as meters.
This is part of issue #18

Path planning improvements

---

grinding_rviz_plugin/src/grinding_rviz_plugin.cpp
grinding_rviz_plugin/src/scanning_widget.cpp
grinding_rviz_plugin/src/scanning_widget.h

@VictorLamoine Ready for review

Skip alignment and comparison widget -- Demonstrator

---

scanning/src/scanning.cpp

Fixes #36 
@VictorLamoine I didn't test it on fanuc grinding but it's ok on my little application which was used to identify this bug. 
Ready for review.

Fix bug in point cloud / mesh transformation

---

grinding_rviz_plugin/src/path_planning_widget.cpp
grinding_rviz_plugin/src/path_planning_widget.h

- Minor simplifications
- Added `setRange` to avoid possible wrong user values

Simplify path planning widget

---

grinding_rviz_plugin/src/path_planning_widget.cpp
grinding_rviz_plugin/src/path_planning_widget.h
path_planning/src/path_planning.cpp
path_planning/srv/PathPlanningService.srv

@VictorLamoine I had some problem with merge conflict. So I prefered create a new branch and deal with merge conflicts with this branch.
Normally merge is OK here.
Ready for review.

Add surfacing mode in path planning widget and service (cleaned)

---

grinding_rviz_plugin/src/grinding_rviz_plugin.cpp
grinding_rviz_plugin/src/grinding_rviz_plugin.h
grinding_rviz_plugin/src/path_planning_widget.cpp
grinding_rviz_plugin/src/path_planning_widget.h
grinding_rviz_plugin/src/post_processor_widget.cpp
grinding_rviz_plugin/src/post_processor_widget.h
post_processor/srv/PostProcessorService.srv

Send robot poses data from path planning widget to post processor widget

---

path_planning/src/path_planning.cpp

Bezier constructor was changed:
https://github.com/ros-industrial-consortium/bezier/pull/80

Fix compilation with last Bezier version

---

grinding_rviz_plugin/src/path_planning_widget.cpp
grinding_rviz_plugin/src/path_planning_widget.h

Remove/move un-used variables

---

grinding_rviz_plugin/src/scanning_widget.cpp

@KevinBollore ready for review

Do not enable next panel if service failed

---

.gitignore
grinding_rviz_plugin/config/robot_state_visualize.rviz
grinding_rviz_plugin/src/grinding_rviz_plugin.cpp
grinding_rviz_plugin/src/grinding_rviz_plugin.h
grinding_rviz_plugin/src/post_processor_widget.cpp
grinding_rviz_plugin/src/post_processor_widget.h
grinding_rviz_plugin/tp_programs/README.md
post_processor/CMakeLists.txt
post_processor/package.xml
post_processor/src/post_processor.cpp
post_processor/srv/PostProcessorService.srv

Improve / finish GUI
Program location is now set by a fixed value: 
https://github.com/InstitutMaupertuis/fanuc_grinding/pull/47/files#diff-2cf2a9843953106c17cd22e22b8834a1R221
Add `sendMsgBox` in the widget
Check service return status
rename `getRobotPosesData` to `getRobotTrajectoryData`

Improve post-processor GUI and service

---

grinding_rviz_plugin/src/alignment_widget.cpp
grinding_rviz_plugin/src/comparison_widget.cpp
grinding_rviz_plugin/src/path_planning_widget.cpp
grinding_rviz_plugin/src/post_processor_widget.cpp
grinding_rviz_plugin/src/scanning_widget.cpp
path_planning/src/path_planning.cpp
publish_meshfile/src/publish_meshfile.cpp
scanning/src/scanning.cpp

Improve ROS STREAM output

---

grinding_rviz_plugin/src/alignment_widget.cpp
grinding_rviz_plugin/src/comparison_widget.cpp
grinding_rviz_plugin/src/grinding_rviz_plugin.cpp
grinding_rviz_plugin/src/path_planning_widget.cpp
grinding_rviz_plugin/src/post_processor_widget.cpp
grinding_rviz_plugin/src/scanning_widget.cpp

Ready for review.
Cosmetics only
```
find . -type f -exec sed -i 's/this->//g' {} \;
```

Remove this-> everywhere

---

alignment/src/alignment.cpp
comparison/src/comparison.cpp
execute_joint_state/src/execute_joint_state.cpp
path_planning/src/path_planning.cpp
publish_meshfile/src/publish_meshfile.cpp
scanning/src/scanning.cpp

Stop spinner before returning

---

alignment/CMakeLists.txt
alignment/package.xml
comparison/CMakeLists.txt
comparison/package.xml
comparison/src/comparison.cpp
execute_joint_state/CMakeLists.txt
execute_joint_state/package.xml
fanuc_grinding/package.xml
path_planning/CMakeLists.txt
path_planning/package.xml
post_processor/CMakeLists.txt
post_processor/package.xml
publish_meshfile/CMakeLists.txt
publish_meshfile/package.xml
publish_meshfile/src/publish_meshfile.cpp
rviz_plugin/CMakeLists.txt
rviz_plugin/package.xml
scanning/CMakeLists.txt
scanning/package.xml

Fixes #66 and #52 
@KevinBollore please test with both catkin_make and catkin_build
Don't forget to remove the build and devel directories before each build.

Improve packages

---

comparison/src/comparison.cpp
path_planning/src/path_planning.cpp

Fix service function names

---

.travis.yml
publish_meshfile/CMakeLists.txt
publish_meshfile/package.xml

Fix travis

---

rviz_plugin/src/comparison_widget.h
rviz_plugin/src/fanuc_grinding_rviz_plugin.cpp

Add sendMsgBox in comparison widget

---

rviz_plugin/src/fanuc_grinding_rviz_plugin.cpp

Eclipse auto format on connect calls

---

documentation/launcher/README.md

@KevinBollore don't forget to update your desktop file

Fix desktop file

---

comparison/CMakeLists.txt
comparison/package.xml
comparison/src/comparison.cpp
execute_joint_state/src/execute_joint_state.cpp
path_planning/src/path_planning.cpp
post_processor/src/post_processor.cpp
publish_meshfile/src/publish_meshfile.cpp
rviz_plugin/src/alignment_widget.cpp
rviz_plugin/src/alignment_widget.h
rviz_plugin/src/comparison_widget.cpp
rviz_plugin/src/comparison_widget.h
rviz_plugin/src/fanuc_grinding_rviz_plugin.cpp
rviz_plugin/src/fanuc_grinding_rviz_plugin.h
rviz_plugin/src/path_planning_widget.cpp
rviz_plugin/src/path_planning_widget.h
rviz_plugin/src/post_processor_widget.cpp
rviz_plugin/src/post_processor_widget.h
rviz_plugin/src/scanning_widget.cpp
rviz_plugin/src/scanning_widget.h
scanning/src/scanning.cpp

Simplify includes

---

.gitignore
post_processor/CMakeLists.txt
post_processor/package.xml
post_processor/src/post_processor.cpp
post_processor/srv/PostProcessorService.srv
rviz_plugin/src/post_processor_widget.cpp
rviz_plugin/src/post_processor_widget.h

:construction: PR in construction :construction:

Improve post processor service and widget

---

rviz_plugin/src/post_processor_widget.cpp

- Remove .LS extension instead of adding it
- Tweak program name at start-up

Remove .LS extension instead of adding it

---

rviz_plugin/src/alignment_widget.h
rviz_plugin/src/comparison_widget.cpp
rviz_plugin/src/comparison_widget.h
rviz_plugin/src/fanuc_grinding_rviz_plugin.cpp
rviz_plugin/src/fanuc_grinding_rviz_plugin.h
rviz_plugin/src/path_planning_widget.h
rviz_plugin/src/post_processor_widget.cpp
rviz_plugin/src/post_processor_widget.h
rviz_plugin/src/scanning_widget.h

Improve coding style

---

rviz_plugin/src/alignment_widget.cpp
rviz_plugin/src/alignment_widget.h
rviz_plugin/src/comparison_widget.cpp
rviz_plugin/src/comparison_widget.h
rviz_plugin/src/fanuc_grinding_rviz_plugin.cpp
rviz_plugin/src/fanuc_grinding_rviz_plugin.h
rviz_plugin/src/path_planning_widget.cpp
rviz_plugin/src/path_planning_widget.h
rviz_plugin/src/post_processor_widget.h
rviz_plugin/src/scanning_widget.cpp
rviz_plugin/src/scanning_widget.h

Pass structure by reference, add const where possible

---

rviz_plugin/src/alignment_widget.cpp
rviz_plugin/src/alignment_widget.h
rviz_plugin/src/comparison_widget.cpp
rviz_plugin/src/comparison_widget.h
rviz_plugin/src/path_planning_widget.cpp
rviz_plugin/src/path_planning_widget.h
rviz_plugin/src/scanning_widget.cpp
rviz_plugin/src/scanning_widget.h

Remove service request params private members
